### ISSUE TITLE
Try to use iterm2 backend, but raise UsageError: Invalid GUI request 'iterm2'

### ISSUE THREAD

**Issue by dingo9** [oselivanov/matplotlib_iterm2#1]
Thank you for making such good project.

When I try to use iterm2 as the backend of my mac, after following the step by step which in README file, still raise such exception.

```
UsageError: Invalid GUI request 'iterm2', valid ones are: pyglet, osx, qt5, qt, glut, gtk, gtk3, tk, wx
```

iterm version : Build 2.9.20151006-nightly
ipython version: IPython 4.0.0
matpoltlib version: 1.4.3

I tried to solve such problem for weeks, but still don't work....

**Comment by oselivanov** [comment]
Ignore that, it should work anyway.
1. Do you have imgcat in your PATH?
2. Have you checked that it actually works by displaying some plot?

**Comment by oselivanov** [comment]
Just added a note to README.

**Comment by dingo9** [comment]
cool! It works~ 
Just ignore that, it works well, Thank you very much!
